// ─────────────────────────────────────────────────────────
// Integrated Form Builder — Field Registry (30+ fields)
// ─────────────────────────────────────────────────────────

import type { FBFieldDef, FBFieldType } from "./types"

export const FIELD_CATEGORIES = [
  { key: "basic", label: "Basic Fields", description: "Common input types" },
  { key: "advanced", label: "Advanced Fields", description: "Rich input types" },
  { key: "school", label: "School Fields", description: "Education-specific fields" },
  { key: "layout", label: "Layout", description: "Structure & presentation" },
] as const

export const FIELD_REGISTRY: Record<FBFieldType, FBFieldDef> = {
  // ── Basic Fields ──────────────────────────────────────

  SHORT_TEXT: {
    type: "SHORT_TEXT",
    label: "Short Text",
    icon: "Type",
    category: "basic",
    description: "Single-line text input",
    isLayout: false,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: true,
    supportsConditional: true,
    defaultProps: {
      label: "Short Text",
      name: "short_text",
      placeholder: "Enter text...",
      width: "full",
      isRequired: false,
      validations: {},
    },
    propSchema: [
      { key: "placeholder", label: "Placeholder", type: "text" },
      { key: "defaultValue", label: "Default Value", type: "text" },
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "tooltip", label: "Tooltip", type: "text" },
      { key: "width", label: "Width", type: "select", options: [{ label: "Full", value: "full" }, { label: "Half", value: "half" }, { label: "Third", value: "third" }, { label: "Two-Thirds", value: "two-thirds" }] },
      { key: "isRequired", label: "Required", type: "boolean" },
      { key: "isReadOnly", label: "Read Only", type: "boolean" },
    ],
  },

  LONG_TEXT: {
    type: "LONG_TEXT",
    label: "Long Text",
    icon: "AlignLeft",
    category: "basic",
    description: "Multi-line text area",
    isLayout: false,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: true,
    supportsConditional: true,
    defaultProps: {
      label: "Long Text",
      name: "long_text",
      placeholder: "Enter detailed text...",
      width: "full",
      isRequired: false,
      validations: {},
    },
    propSchema: [
      { key: "placeholder", label: "Placeholder", type: "text" },
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "width", label: "Width", type: "select", options: [{ label: "Full", value: "full" }, { label: "Half", value: "half" }] },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  RICH_TEXT: {
    type: "RICH_TEXT",
    label: "Rich Text",
    icon: "FileText",
    category: "basic",
    description: "Formatted text with bold, italic, lists",
    isLayout: false,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: true,
    supportsConditional: true,
    defaultProps: {
      label: "Rich Text",
      name: "rich_text",
      width: "full",
      isRequired: false,
      validations: {},
    },
    propSchema: [
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "width", label: "Width", type: "select", options: [{ label: "Full", value: "full" }, { label: "Half", value: "half" }] },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  EMAIL: {
    type: "EMAIL",
    label: "Email",
    icon: "Mail",
    category: "basic",
    description: "Email address input with validation",
    isLayout: false,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: true,
    supportsConditional: true,
    defaultProps: {
      label: "Email Address",
      name: "email",
      placeholder: "name@example.com",
      width: "half",
      isRequired: false,
      validations: {},
    },
    propSchema: [
      { key: "placeholder", label: "Placeholder", type: "text" },
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "width", label: "Width", type: "select", options: [{ label: "Full", value: "full" }, { label: "Half", value: "half" }] },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  PHONE: {
    type: "PHONE",
    label: "Phone",
    icon: "Phone",
    category: "basic",
    description: "Phone number input",
    isLayout: false,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: true,
    supportsConditional: true,
    defaultProps: {
      label: "Phone Number",
      name: "phone",
      placeholder: "+1 (555) 000-0000",
      width: "half",
      isRequired: false,
      validations: {},
    },
    propSchema: [
      { key: "placeholder", label: "Placeholder", type: "text" },
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "width", label: "Width", type: "select", options: [{ label: "Full", value: "full" }, { label: "Half", value: "half" }] },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  NUMBER: {
    type: "NUMBER",
    label: "Number",
    icon: "Hash",
    category: "basic",
    description: "Numeric input",
    isLayout: false,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: true,
    supportsConditional: true,
    defaultProps: {
      label: "Number",
      name: "number",
      placeholder: "0",
      width: "half",
      isRequired: false,
      validations: {},
    },
    propSchema: [
      { key: "placeholder", label: "Placeholder", type: "text" },
      { key: "defaultValue", label: "Default Value", type: "number" },
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "width", label: "Width", type: "select", options: [{ label: "Full", value: "full" }, { label: "Half", value: "half" }, { label: "Third", value: "third" }] },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  DATE: {
    type: "DATE",
    label: "Date",
    icon: "Calendar",
    category: "basic",
    description: "Date picker",
    isLayout: false,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: true,
    supportsConditional: true,
    defaultProps: {
      label: "Date",
      name: "date",
      width: "half",
      isRequired: false,
      validations: {},
    },
    propSchema: [
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "width", label: "Width", type: "select", options: [{ label: "Full", value: "full" }, { label: "Half", value: "half" }, { label: "Third", value: "third" }] },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  TIME: {
    type: "TIME",
    label: "Time",
    icon: "Clock",
    category: "basic",
    description: "Time picker",
    isLayout: false,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: true,
    supportsConditional: true,
    defaultProps: {
      label: "Time",
      name: "time",
      width: "half",
      isRequired: false,
      validations: {},
    },
    propSchema: [
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "width", label: "Width", type: "select", options: [{ label: "Full", value: "full" }, { label: "Half", value: "half" }, { label: "Third", value: "third" }] },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  DATE_TIME: {
    type: "DATE_TIME",
    label: "Date & Time",
    icon: "CalendarClock",
    category: "basic",
    description: "Combined date and time picker",
    isLayout: false,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: true,
    supportsConditional: true,
    defaultProps: {
      label: "Date & Time",
      name: "date_time",
      width: "half",
      isRequired: false,
      validations: {},
    },
    propSchema: [
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "width", label: "Width", type: "select", options: [{ label: "Full", value: "full" }, { label: "Half", value: "half" }] },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  DROPDOWN: {
    type: "DROPDOWN",
    label: "Dropdown",
    icon: "ChevronDown",
    category: "basic",
    description: "Select from a list of options",
    isLayout: false,
    hasOptions: true,
    hasLinkedData: false,
    supportsValidation: true,
    supportsConditional: true,
    defaultProps: {
      label: "Dropdown",
      name: "dropdown",
      placeholder: "Select an option...",
      width: "full",
      isRequired: false,
      validations: {},
      options: [
        { label: "Option 1", value: "option_1" },
        { label: "Option 2", value: "option_2" },
        { label: "Option 3", value: "option_3" },
      ],
    },
    propSchema: [
      { key: "placeholder", label: "Placeholder", type: "text" },
      { key: "options", label: "Options", type: "options-editor" },
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "width", label: "Width", type: "select", options: [{ label: "Full", value: "full" }, { label: "Half", value: "half" }] },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  RADIO: {
    type: "RADIO",
    label: "Radio Buttons",
    icon: "CircleDot",
    category: "basic",
    description: "Single choice from visible options",
    isLayout: false,
    hasOptions: true,
    hasLinkedData: false,
    supportsValidation: true,
    supportsConditional: true,
    defaultProps: {
      label: "Radio Group",
      name: "radio",
      width: "full",
      isRequired: false,
      validations: {},
      options: [
        { label: "Option A", value: "a" },
        { label: "Option B", value: "b" },
        { label: "Option C", value: "c" },
      ],
    },
    propSchema: [
      { key: "options", label: "Options", type: "options-editor" },
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "width", label: "Width", type: "select", options: [{ label: "Full", value: "full" }, { label: "Half", value: "half" }] },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  CHECKBOX: {
    type: "CHECKBOX",
    label: "Checkboxes",
    icon: "CheckSquare",
    category: "basic",
    description: "Multiple choice selection",
    isLayout: false,
    hasOptions: true,
    hasLinkedData: false,
    supportsValidation: true,
    supportsConditional: true,
    defaultProps: {
      label: "Checkboxes",
      name: "checkboxes",
      width: "full",
      isRequired: false,
      validations: {},
      options: [
        { label: "Choice 1", value: "choice_1" },
        { label: "Choice 2", value: "choice_2" },
        { label: "Choice 3", value: "choice_3" },
      ],
    },
    propSchema: [
      { key: "options", label: "Options", type: "options-editor" },
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "width", label: "Width", type: "select", options: [{ label: "Full", value: "full" }, { label: "Half", value: "half" }] },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  TOGGLE: {
    type: "TOGGLE",
    label: "Toggle / Yes-No",
    icon: "ToggleLeft",
    category: "basic",
    description: "On/off switch",
    isLayout: false,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: false,
    supportsConditional: true,
    defaultProps: {
      label: "Toggle",
      name: "toggle",
      width: "full",
      isRequired: false,
      validations: {},
    },
    propSchema: [
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "defaultValue", label: "Default (on/off)", type: "select", options: [{ label: "Off", value: "false" }, { label: "On", value: "true" }] },
      { key: "width", label: "Width", type: "select", options: [{ label: "Full", value: "full" }, { label: "Half", value: "half" }] },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  // ── Advanced Fields ───────────────────────────────────

  FILE_UPLOAD: {
    type: "FILE_UPLOAD",
    label: "File Upload",
    icon: "Upload",
    category: "advanced",
    description: "Upload images, PDFs, documents",
    isLayout: false,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: true,
    supportsConditional: true,
    defaultProps: {
      label: "File Upload",
      name: "file_upload",
      width: "full",
      isRequired: false,
      validations: { maxFileSize: 5242880, maxFiles: 1 },
      options: { accept: ".pdf,.doc,.docx,.jpg,.jpeg,.png", maxSize: 5242880, multiple: false },
    },
    propSchema: [
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "width", label: "Width", type: "select", options: [{ label: "Full", value: "full" }, { label: "Half", value: "half" }] },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  SIGNATURE: {
    type: "SIGNATURE",
    label: "Signature",
    icon: "PenTool",
    category: "advanced",
    description: "Touch/mouse signature pad",
    isLayout: false,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: false,
    supportsConditional: true,
    defaultProps: {
      label: "Signature",
      name: "signature",
      width: "full",
      isRequired: false,
      validations: {},
    },
    propSchema: [
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "width", label: "Width", type: "select", options: [{ label: "Full", value: "full" }, { label: "Half", value: "half" }] },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  RATING: {
    type: "RATING",
    label: "Rating",
    icon: "Star",
    category: "advanced",
    description: "Star or scale rating",
    isLayout: false,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: false,
    supportsConditional: true,
    defaultProps: {
      label: "Rating",
      name: "rating",
      width: "half",
      isRequired: false,
      validations: {},
      options: { max: 5, icon: "star" },
    },
    propSchema: [
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "width", label: "Width", type: "select", options: [{ label: "Full", value: "full" }, { label: "Half", value: "half" }] },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  SLIDER: {
    type: "SLIDER",
    label: "Slider",
    icon: "SlidersHorizontal",
    category: "advanced",
    description: "Numeric range slider",
    isLayout: false,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: true,
    supportsConditional: true,
    defaultProps: {
      label: "Slider",
      name: "slider",
      width: "full",
      isRequired: false,
      validations: {},
      options: { min: 0, max: 100, step: 1 },
    },
    propSchema: [
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "width", label: "Width", type: "select", options: [{ label: "Full", value: "full" }, { label: "Half", value: "half" }] },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  ADDRESS: {
    type: "ADDRESS",
    label: "Address",
    icon: "MapPin",
    category: "advanced",
    description: "Structured address fields",
    isLayout: false,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: true,
    supportsConditional: true,
    defaultProps: {
      label: "Address",
      name: "address",
      width: "full",
      isRequired: false,
      validations: {},
      options: { showStreet: true, showCity: true, showState: true, showZip: true, showCountry: true },
    },
    propSchema: [
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "width", label: "Width", type: "select", options: [{ label: "Full", value: "full" }] },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  // ── School-Specific Fields ────────────────────────────

  GUARDIAN_SELECTOR: {
    type: "GUARDIAN_SELECTOR",
    label: "Guardian Selector",
    icon: "Users",
    category: "school",
    description: "Select a guardian from the system",
    isLayout: false,
    hasOptions: false,
    hasLinkedData: true,
    supportsValidation: false,
    supportsConditional: true,
    defaultProps: {
      label: "Select Guardian",
      name: "guardian_id",
      width: "full",
      isRequired: false,
      validations: {},
      linkedModel: "Guardian",
      linkedField: "id",
    },
    propSchema: [
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "width", label: "Width", type: "select", options: [{ label: "Full", value: "full" }, { label: "Half", value: "half" }] },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  STUDENT_SELECTOR: {
    type: "STUDENT_SELECTOR",
    label: "Student Selector",
    icon: "GraduationCap",
    category: "school",
    description: "Select a student from the system",
    isLayout: false,
    hasOptions: false,
    hasLinkedData: true,
    supportsValidation: false,
    supportsConditional: true,
    defaultProps: {
      label: "Select Student",
      name: "student_id",
      width: "full",
      isRequired: false,
      validations: {},
      linkedModel: "Student",
      linkedField: "id",
    },
    propSchema: [
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "width", label: "Width", type: "select", options: [{ label: "Full", value: "full" }, { label: "Half", value: "half" }] },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  STAFF_SELECTOR: {
    type: "STAFF_SELECTOR",
    label: "Staff Selector",
    icon: "UserCog",
    category: "school",
    description: "Select a staff member from the system",
    isLayout: false,
    hasOptions: false,
    hasLinkedData: true,
    supportsValidation: false,
    supportsConditional: true,
    defaultProps: {
      label: "Select Staff",
      name: "staff_id",
      width: "full",
      isRequired: false,
      validations: {},
      linkedModel: "User",
      linkedField: "id",
    },
    propSchema: [
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "width", label: "Width", type: "select", options: [{ label: "Full", value: "full" }, { label: "Half", value: "half" }] },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  CLASS_SELECTOR: {
    type: "CLASS_SELECTOR",
    label: "Class Selector",
    icon: "School",
    category: "school",
    description: "Select a class/cohort",
    isLayout: false,
    hasOptions: false,
    hasLinkedData: true,
    supportsValidation: false,
    supportsConditional: true,
    defaultProps: {
      label: "Select Class",
      name: "class_id",
      width: "half",
      isRequired: false,
      validations: {},
      linkedModel: "Class",
      linkedField: "id",
    },
    propSchema: [
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "width", label: "Width", type: "select", options: [{ label: "Full", value: "full" }, { label: "Half", value: "half" }] },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  SESSION_SELECTOR: {
    type: "SESSION_SELECTOR",
    label: "Academic Session",
    icon: "BookOpen",
    category: "school",
    description: "Select an academic session/term",
    isLayout: false,
    hasOptions: false,
    hasLinkedData: true,
    supportsValidation: false,
    supportsConditional: true,
    defaultProps: {
      label: "Academic Session",
      name: "session_id",
      width: "half",
      isRequired: false,
      validations: {},
      linkedModel: "AcademicSession",
      linkedField: "id",
    },
    propSchema: [
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "width", label: "Width", type: "select", options: [{ label: "Full", value: "full" }, { label: "Half", value: "half" }] },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  MEDICAL_INFO: {
    type: "MEDICAL_INFO",
    label: "Medical Info",
    icon: "Stethoscope",
    category: "school",
    description: "Medical information block (allergies, conditions, medications)",
    isLayout: false,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: false,
    supportsConditional: true,
    defaultProps: {
      label: "Medical Information",
      name: "medical_info",
      width: "full",
      isRequired: false,
      validations: {},
      options: { showAllergies: true, showConditions: true, showMedications: true, showBloodType: true, showDoctorInfo: true },
    },
    propSchema: [
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  BEHAVIORAL_OBSERVATION: {
    type: "BEHAVIORAL_OBSERVATION",
    label: "Behavioral Observation",
    icon: "Eye",
    category: "school",
    description: "Structured behavioral observation form",
    isLayout: false,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: false,
    supportsConditional: true,
    defaultProps: {
      label: "Behavioral Observation",
      name: "behavioral_observation",
      width: "full",
      isRequired: false,
      validations: {},
      options: { showBehaviorType: true, showSeverity: true, showContext: true, showActionTaken: true, showFollowUp: true },
    },
    propSchema: [
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  ASSESSMENT_RUBRIC: {
    type: "ASSESSMENT_RUBRIC",
    label: "Assessment Rubric",
    icon: "ClipboardCheck",
    category: "school",
    description: "Rubric-based assessment grid",
    isLayout: false,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: false,
    supportsConditional: true,
    defaultProps: {
      label: "Assessment Rubric",
      name: "assessment_rubric",
      width: "full",
      isRequired: false,
      validations: {},
      options: {
        criteria: [
          { name: "Criterion 1", levels: ["Excellent", "Good", "Satisfactory", "Needs Improvement"] },
          { name: "Criterion 2", levels: ["Excellent", "Good", "Satisfactory", "Needs Improvement"] },
        ],
      },
    },
    propSchema: [
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  ATTENDANCE_JUSTIFICATION: {
    type: "ATTENDANCE_JUSTIFICATION",
    label: "Attendance Justification",
    icon: "CalendarX",
    category: "school",
    description: "Absence/late justification with date and reason",
    isLayout: false,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: false,
    supportsConditional: true,
    defaultProps: {
      label: "Attendance Justification",
      name: "attendance_justification",
      width: "full",
      isRequired: false,
      validations: {},
      options: { showDate: true, showType: true, showReason: true, showAttachment: true, types: ["Absent", "Late", "Early Leave"] },
    },
    propSchema: [
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  EMERGENCY_CONTACT: {
    type: "EMERGENCY_CONTACT",
    label: "Emergency Contact",
    icon: "ShieldAlert",
    category: "school",
    description: "Emergency contact block (name, phone, relationship)",
    isLayout: false,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: true,
    supportsConditional: true,
    defaultProps: {
      label: "Emergency Contact",
      name: "emergency_contact",
      width: "full",
      isRequired: false,
      validations: {},
      options: { contacts: 2, showRelationship: true, showAddress: false },
    },
    propSchema: [
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  CONSENT_AGREEMENT: {
    type: "CONSENT_AGREEMENT",
    label: "Consent / Agreement",
    icon: "FileCheck",
    category: "school",
    description: "Legal consent with checkbox agreement",
    isLayout: false,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: false,
    supportsConditional: true,
    defaultProps: {
      label: "Consent",
      name: "consent",
      width: "full",
      isRequired: true,
      validations: {},
      options: { consentText: "I agree to the terms and conditions.", showFullText: true, requireSignature: false },
    },
    propSchema: [
      { key: "helpText", label: "Help Text", type: "text" },
      { key: "isRequired", label: "Required", type: "boolean" },
    ],
  },

  // ── Layout Fields ─────────────────────────────────────

  SECTION_BREAK: {
    type: "SECTION_BREAK",
    label: "Section Break",
    icon: "Minus",
    category: "layout",
    description: "Visual section divider with optional title",
    isLayout: true,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: false,
    supportsConditional: true,
    defaultProps: {
      label: "Section Title",
      name: "section_break",
      width: "full",
      isRequired: false,
      validations: {},
      description: "Optional section description",
    },
    propSchema: [
      { key: "description", label: "Description", type: "textarea" },
    ],
  },

  PAGE_BREAK: {
    type: "PAGE_BREAK",
    label: "Page Break",
    icon: "FileStack",
    category: "layout",
    description: "Start a new page/step in multi-step forms",
    isLayout: true,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: false,
    supportsConditional: false,
    defaultProps: {
      label: "Next Page",
      name: "page_break",
      width: "full",
      isRequired: false,
      validations: {},
    },
    propSchema: [],
  },

  HEADING: {
    type: "HEADING",
    label: "Heading",
    icon: "Heading",
    category: "layout",
    description: "Display heading text",
    isLayout: true,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: false,
    supportsConditional: true,
    defaultProps: {
      label: "Heading Text",
      name: "heading",
      width: "full",
      isRequired: false,
      validations: {},
      options: { level: "h2" },
    },
    propSchema: [
      { key: "label", label: "Heading Text", type: "text" },
    ],
  },

  PARAGRAPH: {
    type: "PARAGRAPH",
    label: "Paragraph",
    icon: "AlignJustify",
    category: "layout",
    description: "Display informational text",
    isLayout: true,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: false,
    supportsConditional: true,
    defaultProps: {
      label: "Paragraph",
      name: "paragraph",
      width: "full",
      isRequired: false,
      validations: {},
      description: "Enter your informational text here.",
    },
    propSchema: [
      { key: "description", label: "Text Content", type: "textarea" },
    ],
  },

  DIVIDER: {
    type: "DIVIDER",
    label: "Divider",
    icon: "SeparatorHorizontal",
    category: "layout",
    description: "Horizontal line separator",
    isLayout: true,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: false,
    supportsConditional: false,
    defaultProps: {
      label: "Divider",
      name: "divider",
      width: "full",
      isRequired: false,
      validations: {},
    },
    propSchema: [],
  },

  HIDDEN: {
    type: "HIDDEN",
    label: "Hidden Field",
    icon: "EyeOff",
    category: "layout",
    description: "Hidden field for tracking data",
    isLayout: true,
    hasOptions: false,
    hasLinkedData: false,
    supportsValidation: false,
    supportsConditional: false,
    defaultProps: {
      label: "Hidden",
      name: "hidden",
      width: "full",
      isRequired: false,
      isHidden: true,
      validations: {},
    },
    propSchema: [
      { key: "defaultValue", label: "Value", type: "text" },
    ],
  },
}

export function getFieldDef(type: FBFieldType): FBFieldDef {
  return FIELD_REGISTRY[type]
}

export function getFieldsByCategory(category: string): FBFieldDef[] {
  return Object.values(FIELD_REGISTRY).filter((f) => f.category === category)
}

export function getAllFields(): FBFieldDef[] {
  return Object.values(FIELD_REGISTRY)
}

export function isLayoutField(type: FBFieldType): boolean {
  return FIELD_REGISTRY[type]?.isLayout ?? false
}
